### ISSUE TITLE
Enhancement: Implement email template library

### ISSUE THREAD

**Issue by hassanelsherbiny** [titianamuhler/WeCareCRM#12]
Streamline email communication by implementing a library of pre-defined email templates that users can customize and use for common scenarios (e.g., welcome emails, follow-up emails, newsletters). Email templates save time and ensure consistency in email messaging across the organization. The template library should support rich text formatting, dynamic placeholders for personalized content, and categorization/tagging for easy navigation. Allow users to create, edit, and share custom templates to meet their specific communication needs.

**Comment by titianamuhler** [comment]
thanks for your suggestion but currently this is not planed
